### ISSUE TITLE
I got 95.33% top1 with evo_resnet50(b0) on cifar10.

### ISSUE THREAD

**Issue by DevinXYang** [digantamisra98/EvoNorm#3]
Implement and example could refer to [impl](https://github.com/PistonY/ModelZoo.pytorch/blob/master/models/evo_norm.py) and [train code](https://github.com/PistonY/ModelZoo.pytorch/blob/master/scripts/train_sample.py).

I didn't struggle with training settings btw.

**Comment by DevinXYang** [comment]
Training setting is `bs=64, 1GPU, wd=1e-4, lr=0.1(cosine), epochs=200`

**Comment by digantamisra98** [comment]
Fixed my B0 code based on your implementation. Thanks!
