### ISSUE TITLE
Improvement on group_std in EvoNorm2D

### ISSUE THREAD

**Issue by zwep** [digantamisra98/EvoNorm#6]
Hi,

to make easy use of the layer, I noticed that it can help to add a `groups` argument to the initialization of the layer. This groups argument can then be given to the `group_std` calculation to adjust for the amount of groups that one wants to define.
Otherwise you are stuck with the default value of `32`.

Kind regards

**Comment by digantamisra98** [comment]
Fixed in [
bc8ae55](https://github.com/digantamisra98/EvoNorm/commit/bc8ae55d5615c56bb66c39c2a3ce9d47ffe6863b)
