### ISSUE TITLE
l34 raises an error

### ISSUE THREAD

**Issue by benjamin-du** [digantamisra98/EvoNorm#8]
```
def __init__(self, input, non_linear = True, version = 'S0', efficien affine = True,
```

There is a space between efficien and affine. Not sure what should be written instead (erase "efficien" ?)

**Comment by digantamisra98** [comment]
Hi. 
Thanks for pointing that error. I have fixed it now. The parameter `efficient` is simply a boolean parameter to consider using Memory Efficient Version of Swish for S0 or not.
